* Buku Programming

** Daftar Isi
:PROPERTIES:
:TOC:      :include all siblings :depth 2
:END:

:CONTENTS:
- [[#buku-programming][Buku Programming]]
  - [[#daftar-isi][Daftar Isi]]
  - [[#intro][Intro]]
  - [[#konten-umum][Konten Umum]]
    - [[#screen-cast---cerita-programmer][Screen Cast - Cerita Programmer]]
  - [[#coming-soon][Coming soon]]
    - [[#tutorial-bahasa-pemrograman][Tutorial Bahasa Pemrograman]]
  - [[#license][License]]
:END:

** Intro

Halo, nama gw Yoka, saat ini gw kerja sebagai Senior Frontend Engineer di Ruang Guru, salah satu perusahaan teknologi di Indonesia yang bergerak di bidang pendidikan. Berbeda dari sebagian besar orang yang kerja jadi programmer, gw bukan berasal dari background pendidikan ilmu komputer/informatika. Setelah melewati berbagi macam proses /denial/ dan /dropout/ dari kampus s2 gw, akhirnya gw memutuskan buat ngejar mimpi gw untuk jadi programmer. Dan sampai saat ini, gw merasa itu adalah salah satu keputusan terbaik di dalam hidup gw (selain nikahin istri gw :p) +setelah belajar vim dan emacs+.

Buat gw pribadi, menjadi programmer itu adalah salah satu hal yang paling menyenangkan dan memiliki timbal balik finansial yang mencukupi, dan gw pengen berbagi itu semua ke banyak orang! Gw punya mimpi agar suatu saat nanti ilmu yang gw punya bisa dipake oleh banyak orang untuk mengubah hidupnya menjadi lebih baik (secara finansial dan juga non finansial). Dan /repository/ ini adalah salah satu langkah awal untuk menuju ke sana.

Mungkin pertanyaan berikutnya adalah kenapa dalam bentuk repository? Dan kenapa bukan dalam bentuk website atau sejenisnya? Ada beberapa alasan:

1. Repository git seperti ini adalah salah satu perangkat yang paling sering dipakai oleh programmer, jadi dengan dibuatnya buku ini di sini, maka pembaca akan lebih gampang mengeksplor apa yang ada di sini dalam buku ini.
  
2. Gw pengen lebih fokus ke konten yang disampaikan dan bukan ke platformnya. Mungkin akan ada saatnya nanti kalo

3. Di masa depan, akan ada tutorial programming juga di sini, dan akan mudah ketika semuanya berada dalam 1 tempat (untuk dibaca ataupun ditulis).

4. Gw nulis semua ini di emacs, dan org-mode, salah satu keunggulannya adalah buat para pembaca yang mau eksplor lebih jauh tentang buku ini, dan nge-/fork/ atau clone buku ini terus jalanin repo ini di emacs, bakal dapet bonus buat bisa jalanin apa yang ada di buku via org-mode. Salah satu bonusnya adalah bisa punya semacam catetan yang bisa berfungsi sebagai REPL juga.

Sebagai penutup, ada satu kata-kata yang gw baca di buku [[https://www.manning.com/books/get-programming-with-haskell]["Get Programming with Haskell" (Will Kurt, 2018)]] yang terngiang-ngiang dia kepala gw ketika gw menulis (ataupun rekaman) buku ini:

#+BEGIN_QUOTE
Ask yourself, as a reader, what piece of writing in all the world ... would [you] most want to read if [you] had [your] heart's choice. The next step is terrible, but so simple I can hardly believe it as I write it. You just sit down shamelessly and write the thing yourself

J.D. Salinger
#+END_QUOTE

Mungkin sudah saatnya saya mulai berbagi secara lebih terstruktur tentang dunia programming ini. Semoga bisa pelan-pelan membantu banyak orang yang membutuhkan.

** Konten Umum

*** [[./cerita-programmer/README.org][Screen Cast - Cerita Programmer]]

** Coming soon

*** Tutorial Bahasa Pemrograman

** License

[[https://creativecommons.org/licenses/by-nc/3.0/][Creative Commons Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)]]
