#+Title: Umum - Stop Pake Bajakan

[[https://www.youtube.com/watch?v=Z1lri7YKlsY][YouTube Link]]

* Description

Hai guys, setelah kemarin ngebahas tentang persiapan transisi jadi programmer, kali ini gw mau ngomongin sesuatu yang gw anggap penting buat gw sampein sebelum kita ngomongin lebih jauh tentang transisi ini: JANGAN PAKE BAJAKAN! Kenapa? Karena itu adalah hal yang salah, dan sebenernya kita gak perlu ngebajak untuk transisi jadi programmer (bahkan untuk jadi programmer yang jago!).

Tautan:

1. Eloquent JavaScript: https://eloquentjavascript.net/

2. freeCodeCamp: https://www.freecodecamp.org/

* 1/9 Apa

Stop pembajakan

* 2/9 Kayak yang kita tau

Banyak banget sumber belajar berbayar yang bagus banget di luar sana

Buku, Video, Semuanya

Dan gak semuanya punya harga yang murah

* 3/9 Psstt

Gw juga dulu pernah ngebajak waktu jaman kuliah

Kayak game, dan buku-buku gitu dulu gw banyak banget ngebajak

Tapi itu gak bener! Dan gw gak bangga sama hal itu

* 4/9 Kenapa?

Kita ngambil sesuatu yang bukan hak kita!

Dan kita harusnya malu buat ngelakuin hal itu!

* 5/9 Kesel sama koruptor?

Mereka juga ngambil sesuatu yang jelas-jelas bukan hak mereka

* 6/9 Mau gak kalo barang kita diambil semena-mena?

Ei ei!!! Waka waka ei ei!!!

Kalo gw sih enggak

* 7/9 Tapi kan mahal - 1

Bukan berarti lo boleh ngelakuin itu!

Yah karena emang bikinnya gak gampang

Kayak video ini, durasi sekitar 10 menit, tapi total waktu bikinnya bisa sampe lebih dari 2 jam

Buku juga gitu

* 8/9 Tapi kan mahal - 2

Inget, kalo sebenernya kita gak perlu buku itu buat jadi jago

Masih banyak kok sumber gratis yang gak kalah bagusnya!

* 9/9 Jadi

Jangan ngebajak dan pake bajakan!

Karena emang gak ada alasan buat itu!
